---
date: 2021-10-30 19:31:49
draft: true
iso8601: 2021-10-30T19:31:49+09:00
tags:
  - undef
title: 'try { ... } catch { ... }; でうっかりハマったので調べてみた'

---

[@nqounet](https://twitter.com/nqounet)です。

`Try::Tiny`は便利なのですが、妙なところでハマってしまいます。

## 原因

`use Try::Tiny;`を書いてなかっただけなのです。

## どんな状況だったか

とりあえず、失敗したらそのレコードのIDを返すようにしていました。

コードのイメージはこんな感じ。

```perl
my $obj;
try {
  $obj = MyObj->new($row);
}
catch {
  return $row->id;
};
...
```

で、テストを書いて実行すると、何故かIDが返ってくるのでおかしいなと。

どんなエラーなのかと、`p $_;`をcatchに入れてみたのですが、undefになっていて、頭のなかが「？？」って感じに。

落ち着いてみると、`use Try::Tiny;`を書いてなかっただけでした。

つまり、try部分でエラーがなくてもcatchの中が実行されていた、ということなのです。

## use忘れを防ぎたい（未達）

`use Try::Tiny;`忘れを防ぎたいと思って、何か対策がないかと調べてみたのですが、どうもうまくいく気がしません。

`B::Deparse`を使って、`use Try::Tiny;`せずにtryを使っているスクリプトを表示してみるとなんだかよくわからないことに。

（使い方はこちらを参考に→ [404 Blog Not Found:perl - B::Deparse](http://blog.livedoor.jp/dankogai/archives/50761629.html)）

### 元のスクリプト

```perl
use strict;
use warnings;
try {
    print "try\n";
}
catch {
    print "catch\n";
};
```

### 上記の解析後のスクリプト

```perl
use warnings;
use strict;
try {
    print "try\n"
} (catch {
    print "catch\n"
} );
```

`use Try::Tiny;`すると、以下の様な感じになります。

### Try::Tinyした元のスクリプト

```perl
use strict;
use warnings;
use Try::Tiny;
try {
    print "try\n";
}
catch {
    print "catch\n";
};
```

### 上記の解析後のスクリプト

```perl
use Try::Tiny;
use warnings;
use strict;
try sub {
    print "try\n";
}
, catch(sub {
    print "catch\n";
}
);
```
